### ISSUE TITLE
Windows cannot run/compile mmt file

### ISSUE THREAD

**Issue by chonlei** [MichaelClerx/myokit#181]
Trying to run an example script on 
http://myokit.org/static/download/examples/br-1977.mmt
and return the following error:

```
[01:24:57] Opened C:\Users\user\Downloads\br-1977.mmt
[01:25:00] Running embedded script.
[01:25:04] An error has occurred
[01:25:04] Traceback (most recent call last):
  File "C:\myokit\myokit\myokit\gui\ide.py", line 783, in action_run
    progress=pbar.reporter(),
  File "C:\myokit\myokit\myokit\_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 13, in <module>
  File "C:\myokit\myokit\myokit\_sim\cvode.py", line 126, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "C:\myokit\myokit\myokit\_sim\__init__.py", line 139, in _compile
    return imp.load_dynamic(name, pathname)
ImportError: DLL load failed: The specified module could not be found.
```

using a recently installed myokit (also see #180) on a Windows machine.

**Comment by chonlei** [comment]
See #180, I am using 

- WinPython 2.7.10.3
- Myokit 1.26.3 installer for WinPython (64 bit)

as suggested in http://myokit.org/windows

**Comment by MichaelClerx** [comment]
I can recreate this now on windows 10, with anaconda (python 3.5), and the github version of myokit

**Comment by MichaelClerx** [comment]
@chonlei can you tell me what it says when you open a WinPython command prompt and then type "python"?

e.g.
```
(C:\myokit\anaconda-3-4.2.0) C:\myokit\myokit>python
Python 3.5.5 |Anaconda custom (64-bit)| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by MichaelClerx** [comment]
https://github.com/skvark/opencv-python/issues/36

**Comment by MichaelClerx** [comment]
In my recreation, I can succesfully run a 1d cable simulation, which doesn't depend on cvode, so it's the CVODE dlls that are missing, it seems (or something they depend on?)

**Comment by MichaelClerx** [comment]
Have fixed it on my system by making sure the sundials `lib` directory is on the system `path` environment variable

**Comment by MichaelClerx** [comment]
@chonlei can you tell me what it says when you open a WinPython command prompt and then type "python"?

e.g.
```
(C:\myokit\anaconda-3-4.2.0) C:\myokit\myokit>python
Python 3.5.5 |Anaconda custom (64-bit)| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by MichaelClerx** [comment]
```
C:\Users\cholei\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\myokit\myokit\tools\sundials\lib "/LIBPATH:C:\Program Files\sundials\lib" "/LIBPATH:C:\Program Files (x86)\sundials\lib" /LIBPATH:c:\programdata\anaconda2\libs /LIBPATH:c:\programdata\anaconda2\PCbuild\amd64 /LIBPATH:c:\programdata\anaconda2\PC\VS9.0\amd64 sundials_cvode.lib sundials_nvecserial.lib /EXPORT:initmyokit_sim_1 c:\users\cholei\appdata\local\temp\tmpwjwno0myokit\build\temp.win-amd64-2.7\Release\users\cholei\appdata\local\temp\tmpwjwno0myokit\source.obj /OUT:c:\users\cholei\appdata\local\temp\tmpwjwno0myokit\build\lib.win-amd64-2.7\myokit_sim_1.pyd /IMPLIB:c:\users\cholei\appdata\local\temp\tmpwjwno0myokit\build\temp.win-amd64-2.7\Release\users\cholei\appdata\local\temp\tmpwjwno0myokit\myokit_sim_1.lib /MANIFESTFILE:c:\users\cholei\appdata\local\temp\tmpwjwno0myokit\build\temp.win-amd64-2.7\Release\users\cholei\appdata\local\temp\tmpwjwno0myokit\myokit_sim_1.pyd.manifest
   LINK : fatal error LNK1181: cannot open input file 'sundials_cvode.lib'
```

**Comment by MichaelClerx** [comment]
Could you try running `myokit reset` to remove any old configuration files?

**Comment by MichaelClerx** [comment]
Also, if you followed the new instructions you can remove the older myokit and sundials directories!

**Comment by MichaelClerx** [comment]
So these (if they exist) can go:
  C:\Program Files (x86)\sundials
  C:\Program Files\sundials
  C:\myokit

**Comment by chonlei** [comment]
For the information, I am using Anaconda2 Python 2.7.14:
```
Python 2.7.14 |Anaconda, Inc.| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)] on win32
```

**Comment by chonlei** [comment]
But now everything works after using `myokit reset`. So happy to close this issue. Thank you @MichaelClerx!

**Comment by MichaelClerx** [comment]
Thanks Chon!
