### ISSUE TITLE
Sundials version detection fails on Fedora

### ISSUE THREAD

**Issue by truenicoco** [MichaelClerx/myokit#219]
Using install instructions, on the latest up-to-date fedora.

I believe this might similar to [this](https://github.com/RuleWorld/bionetgen/issues/190).

```$ myokit run example
Reading model from example
File loaded in 0.0285470485687 seconds
Model read successfully
0 validation warning(s) given
Using embedded script
------------------------------------------------------------
  1 import myokit
  2 import matplotlib.pyplot as plt
  3 
  4 # Run simulation
  5 m = get_model()
  6 p = get_protocol()
  7 s = myokit.Simulation(m, p)
  8 s.pre(1000)
  9 d = s.run(1000)
 10 
 11 # Show results
 12 plt.figure()
 13 plt.plot(d['engine.time'], d['membrane.V'])
 14 plt.show()
 15 
------------------------------------------------------------
Traceback (most recent call last):
  File "/user/ncedilni/home/.local/bin/myokit", line 11, in <module>
    sys.exit(main())
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/__main__.py", line 72, in main
    func(**args)
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/__main__.py", line 965, in run
    myokit.run(model, protocol, script)
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/_aux.py", line 1030, in run
    r.run()
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/_aux.py", line 1021, in run
    exec(self.script, environment)
  File "<string>", line 8, in <module>
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/_sim/cvodesim.py", line 141, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/_sim/__init__.py", line 178, in _compile
    raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command 'gcc' failed with exit status 1
Error traceback
Traceback (most recent call last):
  File "/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/_sim/__init__.py", line 167, in _compile
    str('--old-and-unmanageable'),
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: command 'gcc' failed with exit status 1



Compiler output:
    running build
    running build_ext
    building 'myokit_sim_1' extension
    creating /tmp/tmp6MjNC7myokit/build/temp.linux-x86_64-2.7
    creating /tmp/tmp6MjNC7myokit/build/temp.linux-x86_64-2.7/tmp
    creating /tmp/tmp6MjNC7myokit/build/temp.linux-x86_64-2.7/tmp/tmp6MjNC7myokit
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/include -I/opt/local/include -I/user/ncedilni/home/.local/lib/python2.7/site-packages/myokit/_sim -I/usr/include/python2.7 -c /tmp/tmp6MjNC7myokit/source.c -o /tmp/tmp6MjNC7myokit/build/temp.linux-x86_64-2.7/tmp/tmp6MjNC7myokit/source.o
    /tmp/tmp6MjNC7myokit/source.c:14:14: fatal error: cvode/cvode_dense.h: No such file or directory
         #include <cvode/cvode_dense.h>
                  ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
 ```

**Comment by MichaelClerx** [comment]
Thanks Nicolas!

**Comment by MichaelClerx** [comment]
Ok, I think what happened here was that the first time Myokit was run, it couldn't find sundials (not sure why, something with the virtual env?), but it did create a config file. Subsequent runs then scan that config file for a sundials version instead of trying to auto-detect (which is a tiny performance hit)...

Have updated the configuration scheme now to do auto-detection whenever sundials version is not set, and will push this update in a release soon!

For now, could you see if there's a config file `~/.config/myokit/myokit.ini` and add a line `version = 30100` to the sundials section?

**Comment by MichaelClerx** [comment]
@truenicoco You should now be able to 'fix' this by running `pip install myokit` again!
