### ISSUE TITLE
Logging derivatives in OpenCL sim gives unhelpful error message

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#243]
```
[14:04:40] Running embedded script.
[14:04:41] An error has occurred
[14:04:41] Traceback (most recent call last):
  File "/home/michael/dev/myokit/myokit/gui/ide.py", line 798, in action_run
    progress=pbar.reporter(),
  File "/home/michael/dev/myokit/myokit/_aux.py", line 1032, in run
    r.run()
  File "/home/michael/dev/myokit/myokit/_aux.py", line 1023, in run
    myokit._exec(self.script, environment)
  File "/home/michael/dev/myokit/myokit/_exec_new.py", line 17, in _exec
    exec(script, globals, locals)
  File "<string>", line 21, in <module>
  File "/home/michael/dev/myokit/myokit/_sim/openclsim.py", line 713, in run
    r = self._run(duration, log, log_interval, report_nan, progress, msg)
  File "/home/michael/dev/myokit/myokit/_sim/openclsim.py", line 750, in _run
    var = self._model.get(var)
  File "/home/michael/dev/myokit/myokit/_model_api.py", line 1474, in get
    raise KeyError(str(name))
KeyError: 'dot(0'
```

Not supporting this is fine, but the error message should explain things

**Comment by MichaelClerx** [comment]
This works fine:

```
#!/usr/bin/env python3
import myokit

m, p, _ = myokit.load('example')
s = myokit.SimulationOpenCL(m, p)
s.run(5, log=['dot(membrane.V)'])
```

Results in 

```
  File "./ff", line 6, in <module>
    s.run(5, log=['dot(membrane.V)'])
  File "/home/michael/dev/myokit/myokit/_sim/openclsim.py", line 726, in run
    r = self._run(duration, log, log_interval, report_nan, progress, msg)
  File "/home/michael/dev/myokit/myokit/_sim/openclsim.py", line 753, in _run
    precision=self._precision)
  File "/home/michael/dev/myokit/myokit/_datalog.py", line 1862, in prepare_log
    'This log does not support derivatives.')
ValueError: This log does not support derivatives.
```

**Comment by MichaelClerx** [comment]
Tried some other (bad) syntaxes, can't reproduce. Closing this.
