### ISSUE TITLE
Error when installing theano [ubuntu on windows subsystem for linux]

### ISSUE THREAD

**Issue by chonlei** [MichaelClerx/myokit#405]
I created a new virtual env with anaconda and tried to install theano, but it crashes myokit...
```
$ conda create -n theano python=2.7 anaconda
$ source activate theano
$ python fit.py A                                                   # This works
$ conda install numpy scipy mkl
$ conda install theano pygpu
$ python fit.py A                                                   # Now it fails!!
```
The `fit.py` is from https://github.com/CardiacModelling/fickleheart-method-tutorials/blob/master/ion-channel-models/fit.py.

After running the last two conda install, it starts giving me this message
```WARNING:myokit._config:Sundials version not set in myokit.ini and version auto-detection failed.```
Then I thought it was related to #219 , so I tried adding `version = 30100` to the config file `~/.config/myokit/myokit.ini`, or even tried `pip install myokit` again, but it's still not working.

The last error message I got is:
```
$ python fit.py A
Fitting to  data-sinewave.csv
Temperature:  22.0
Fit seed:  542811797
Estimated noise level:  24.44373030673121
Traceback (most recent call last):
  File "fit.py", line 81, in <module>
    temperature=273.15 + info.temperature,  # K
  File "./method/model.py", line 86, in __init__
    self.simulation1 = myokit.Simulation(model, protocol)
  File "/home/chon/anaconda3/envs/theano/lib/python2.7/site-packages/myokit/_sim/cvodesim.py", line 147, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "/home/chon/anaconda3/envs/theano/lib/python2.7/site-packages/myokit/_sim/__init__.py", line 193, in _compile
    raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command '/home/chon/anaconda3/envs/theano/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
Error traceback
Traceback (most recent call last):
  File "/home/chon/anaconda3/envs/theano/lib/python2.7/site-packages/myokit/_sim/__init__.py", line 182, in _compile
    str('--old-and-unmanageable'),
  File "/home/chon/anaconda3/envs/theano/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/chon/anaconda3/envs/theano/lib/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: command '/home/chon/anaconda3/envs/theano/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1

Compiler output:
    running build
    running build_ext
    building 'myokit_sim_1' extension
    creating /tmp/tmpBhybmamyokit/build/temp.linux-x86_64-2.7
    creating /tmp/tmpBhybmamyokit/build/temp.linux-x86_64-2.7/tmp
    creating /tmp/tmpBhybmamyokit/build/temp.linux-x86_64-2.7/tmp/tmpBhybmamyokit
    /home/chon/anaconda3/envs/theano/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/usr/local/include -I/opt/local/include -I/home/chon/anaconda3/envs/theano/lib/python2.7/site-packages/myokit/_sim -I/home/chon/anaconda3/envs/theano/include/python2.7 -c /tmp/tmpBhybmamyokit/source.c -o /tmp/tmpBhybmamyokit/build/temp.linux-x86_64-2.7/tmp/tmpBhybmamyokit/source.o
    /tmp/tmpBhybmamyokit/source.c:6:10: fatal error: cvode/cvode.h: No such file or directory
     #include <cvode/cvode.h>
              ^~~~~~~~~~~~~~~
    compilation terminated.
```

**Comment by MichaelClerx** [comment]
Thanks @chonlei 
Please add the operating system as well

**Comment by MichaelClerx** [comment]
```
$ conda create -n theano python=2.7 anaconda
$ source activate theano
$ python fit.py A                                                   # This works
$ conda install numpy scipy mkl
$ conda install theano pygpu
$ python fit.py A        
```

Could you maybe retry this in a new conda environment? I notice the line installing myokit is missing, but it does seem to be present in your environment

```
 File "/home/chon/anaconda3/envs/theano/lib/python2.7/site-packages/myokit/_sim/cvodesim.py", line 147, in __init__
```

**Comment by MichaelClerx** [comment]
```
    /tmp/tmpBhybmamyokit/source.c:6:10: fatal error: cvode/cvode.h: No such file or directory
     #include <cvode/cvode.h>
```
For some reason, the compiler is unable to find CVODEs header files, while it used to be able to do this.
So that would means something somehow changed either CVODE, some environment variables, or something to do with distutils?

**Comment by chonlei** [comment]
The Operating System for the above error was from the Windows subsystem with Ubuntu 14.04.5 LTS for my testing use, with conda 4.7.11. It's been working fine as normal ubuntu so far, so I am hoping it's not this subsystem creating the unnecessary problem.

**Comment by chonlei** [comment]
Not quite a solution directly to above's issue. Now I tried
```
$ python3 -m pip install --user --upgrade pip
$ python3 -m pip install --user virtualenv
$ cd /path/to/project
$ python3 -m venv env
$ source env/bin/activate
$ pip install --upgrade pip
$ pip3 install myokit
$ cd /path/to/pints
$ pip install .
$ cd -
$ python3 fit.py A                                    # This works
$ pip install pymc3                                   # This has theano and works too!
```
And things works fine like this.

However, I tried this is on Fedora release 26 (Twenty Six)! I gave up the ubuntu subsystem on Windows for now...

**Comment by MichaelClerx** [comment]
Hi @chonlei 
Were you able to reproduce this issue?
