### ISSUE TITLE
Sundials fails on Windows 10

### ISSUE THREAD

**Issue by chonlei** [MichaelClerx/myokit#417]
Hi Michael,

Trying to set up myokit on Windows 10 following http://myokit.org/windows with Miniconda Python 3.7. However, I am getting this error after going through steps 1 to 3 without getting error in between:
```
>python test-myokit.py
WARNING:myokit._config:Sundials version not set in myokit.ini and version auto-detection failed.
Traceback (most recent call last):
  File "D:\Miniconda3\lib\distutils\_msvccompiler.py", line 424, in compile
    self.spawn(args)
  File "D:\Miniconda3\lib\distutils\_msvccompiler.py", line 543, in spawn
    return super().spawn(cmd)
  File "D:\Miniconda3\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "D:\Miniconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "D:\Miniconda3\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'D:\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

... [quite a few of these] ...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 180, in _compile
    str('--old-and-unmanageable'),
  File "D:\Miniconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "D:\Miniconda3\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'D:\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Compiler output:
    running build
    running build_ext
    building 'myokit_sim_1' extension
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users\USER~1
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users\USER~1\AppData
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users\USER~1\AppData\Local
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users\USER~1\AppData\Local\Temp
    creating C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit
    D:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-ID:\some_path\tools\sundials\include" "-IC:\Program Files\sundials\include" "-IC:\Program Files (x86)\sundials\include" -ID:\Miniconda3\lib\site-packages\myokit\_sim -ID:\Miniconda3\include -ID:\Miniconda3\include "-ID:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-ID:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" /TcC:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\source.c /FoC:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\build\temp.win-amd64-3.7\Release\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\source.obj
    source.c
    C:\Users\USER~1\AppData\Local\Temp\tmp2p3wgpjfmyokit\source.c(6): fatal error C1083: Cannot open include file: 'cvode/cvode.h': No such file or directory
```

And I am not getting any error from finding the compiler
```
>python -m myokit compiler
WARNING:myokit._config:Sundials version not set in myokit.ini and version auto-detection failed.
Compilation successful. Found: Microsoft Visual Studio 15.0 (2017) - 192328106
```

Thanks!

**Comment by MichaelClerx** [comment]
Hi Chon,
Those errors mean the compiler can't find sundials. Did you install Myokit from pip or straight from the repository? 

Could you show me the output of `python -m myokit sundials` ?

**Comment by chonlei** [comment]
Hi Michael, I installed Myokit from pip. Yes, I will show you the output later, don't have access to it at the moment.

**Comment by chonlei** [comment]
Hi Michael, yes, I think you are right...
```
>python -m myokit sundials
WARNING:myokit._config:Sundials version not set in myokit.ini and version auto-detection failed.
Sundials not found or compilation failed.
```
But I thought it was not required to be installed separately in Windows (http://myokit.org/windows).

**Comment by MichaelClerx** [comment]
It's not, but the ini file should still point to the right location (somewhere inside the directory where Myokit is installed). Can you check if that's the case?

**Comment by MichaelClerx** [comment]
You can see the location of `myokit.ini` by looking at the output of `python -m myokit system`:

```
== System information ==
Myokit: 1.29.0
Python: 3.7.4 (default, Jul  9 2019, 16:32:37) 

...

= /home/michael/.config/myokit/myokit.ini =
[myokit]
# This file can be used to set global configuration options for Myokit.

...
```

**Comment by chonlei** [comment]
Thank you! So first, the `myokit.ini` did not point to "to the right location (somewhere inside the directory where Myokit is installed)". So I manually added an extra path that points to `...\myokit\_bin\sundials-win-vs\*`, for the `lib` and `include` respectively. I also added the `version = 30100` within the same section. Now, 
```
>python - myokit sundials
Found Sundials version 2.7.0
```
Seems not complaining.

However, I am still getting a very similar error as above, except the last bit, it now complains
`...\source.c(10): fatal error C1083: Cannot open include file: 'sunmatrix/sunmatrix_dense.h': No such file or directory`, instead of `cvode.h`...

**Comment by MichaelClerx** [comment]
Looks like you've got version 2.7.0, which would be `version=27000` in the ini file, can you try that?

**Comment by chonlei** [comment]
Yeah, thank you! That seems to solve the issue. The only thing was that not sure why it couldn't find the path for myokit sundials inside the site-package in my Miniconda3...

**Comment by MichaelClerx** [comment]
Did you have Myokit installed before in a different location?

The .ini file is created automatically when you first run myokit, and on windows it then assumes that you've used the embedded cvode. But if you had myokit installed before there'll already be an ini file, so it won't replace it in case it overrides your manual changes

**Comment by chonlei** [comment]
Might have been! But I can't remember, sorry!
