### ISSUE TITLE
OpenCL detection on OS/X doesn't seem to work

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#514]
Hi @MichaelClerx 
Happy Easter! I was writing some tests for the new importer and suddenly realised that there are some import errors with some myokit modules, even in the master. I installed the package with `pip install -e .[docs,dev,pyqt]` and then ran the minimal tests `python run_tests.py --minimal`. A bunch of seemingly similar errors pop up:
```
======================================================================
ERROR: test_simulation_p (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_simulation_p
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/tests/test_simulation_p.py", line 17, in <module>
    from shared import DIR_DATA, CancellingReporter
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/tests/shared.py", line 33, in <module>
    OpenCL_FOUND = myokit.OpenCL.supported()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 206, in supported
    OpenCL._get_instance()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 90, in _get_instance
    OpenCL()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 65, in __init__
    mname, fname, args, libs, libd, incd)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 197, in _compile
    return load_module(name, d_modul)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 54, in load_module
    module = importlib.util.module_from_spec(spec)
ImportError: dlopen(/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp72ws9tb3myokit/module/myokit_opencl_info_36.cpython-37m-darwin.so, 2): Symbol not found: _clGetDeviceIDs
  Referenced from: /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp72ws9tb3myokit/module/myokit_opencl_info_36.cpython-37m-darwin.so
  Expected in: flat namespace
 in /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp72ws9tb3myokit/module/myokit_opencl_info_36.cpython-37m-darwin.so
```

Have you had this problem before?

_Originally posted by @DavAug in https://github.com/MichaelClerx/myokit/issues/433#issuecomment-611998266_

**Comment by MichaelClerx** [comment]
Seems like it's trying to run the tests, so the OpenCL detection has said "yes I can find OpenCL", but then it's unable to link or something

**Comment by MichaelClerx** [comment]
Oh no it's the supported() check itself that seems to be in trouble

**Comment by MichaelClerx** [comment]
Could be that we need an extra flag when compiling
https://stackoverflow.com/questions/20389345/compile-errors-when-trying-to-determine-opencl-capable-devices-on-a-mac

**Comment by MichaelClerx** [comment]
Adding in the `-framework OpenCL` switch seems to break OpenCL detection entirely

**Comment by MichaelClerx** [comment]
Some details:
```
== System information ==
Myokit: 1.30.4
Python: 3.7.5 (default, Nov  1 2019, 02:16:23)
        [Clang 11.0.0 (clang-1100.0.33.8)]
OS: Darwin (darwin, posix)

== Python requirements ==
NumPy: 1.18.2
SciPy: 1.4.1
Matplotlib: 3.2.1
ConfigParser: OK
Setuptools: 41.2.0

== Python extras ==
SymPy: 1.5.1
CMAES: Not found
MoviePy: Not found

== GUI ==
PyQt5: 5.14.2
  Sip: OK
PyQt4: Not found
PySide: Not found
PySide2: Not found

== Development tools ==
Sphinx: 3.0.0
Flake8: 3.7.9

== Simulation tools ==
Compiler: Clang (Apple LLVM) 11.0.0
Sundials: 5.0.0-dev.2
OpenCL: No OpenCL support detected.

= /Users/david/.config/myokit/myokit.ini =
[myokit]
# This file can be used to set global configuration options for Myokit.

[time]
# Date format used throughout Myokit
# Format should be acceptable for time.strftime
date_format = %Y-%m-%d %H:%M:%S
# Time format used throughout Myokit
time_format = %H:%M:%S

[debug]
# Add line numbers to debug output of simulations
line_numbers = True

[gui]
# Backend to use for graphical user interface.
# Valid options are "pyqt5", "pyqt4" or "pyside".
# Leave unset for automatic selection.
#backend = pyqt5
#backend = pyqt4
#backend = pyside

[sundials]
# Location of sundials shared libary files (.so or .dll).
# Multiple paths can be set using ; as separator.
lib = /usr/local/lib;/opt/local/lib;/usr/local/Cellar/sundials/5.0.0/lib
# Location of sundials header files (.h).
inc = /usr/local/include;/opt/local/include;/usr/local/Cellar/sundials/5.0.0/include
version = 50000

[opencl]
# Location of opencl shared libary files (.so or .dll).
# Multiple paths can be set using ; as separator.
lib = /usr/lib64;/usr/lib64/nvidia;/usr/local/cuda/lib64;/System/Library/Frameworks
# Location of opencl header files (.h).
inc = /usr/include/CL;/usr/local/cuda/include;/System/Library/Frameworks
```
Framework switch isn't recognised: (`myokit opencl`)
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/__main__.py", line 1377, in <module>
    main()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/__main__.py", line 71, in main
    func(**args)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/__main__.py", line 763, in opencl
    print(myokit.OpenCL.info(formatted=True))
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 82, in info
    info = OpenCLInfo(OpenCL._get_instance().info())
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/opencl.py", line 97, in _get_instance
    'OpenCL support not found.\n' + OpenCL._message)
myokit._sim.opencl.NoOpenCLError: OpenCL support not found.
Unable to compile.
Error message:
error: command 'clang' failed with exit status 1
Error traceback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 179, in _compile
    str('--old-and-unmanageable'),
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'clang' failed with exit status 1

Compiler output:
    running build
    running build_ext
    building 'myokit_opencl_info_1' extension
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var/folders
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var/folders/8w
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T
    creating /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/include/CL -I/usr/local/cuda/include -I/System/Library/Frameworks -I/Users/david/Workspace/sabs-r3/myokit/myokit/_sim -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/david/Workspace/sabs-r3/myokit/venv/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/source.c -o /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmpyfmvwtylmyokit/source.o -framework OpenCL
    clang: error: unknown argument: '-framework OpenCL’
```

**Comment by MichaelClerx** [comment]
Unit tests are working on travis os/x now

**Comment by MichaelClerx** [comment]
Apparently not working on all OS/X systems.

@DavAug OpenCL is a framework for GPU/CPU code, that's supported (or definitely used to be) natively by Apple, but also works with nvidia, amd, intel, etc. Myokit uses it for GPU simulations.

Usually it's a hassle to install, so the unit tests detect that there's no OpenCL and skip the OpenCL tests.
In your case, it seems that it _can_ find the header files (C/C++ `.h` files, which tell you about compiled libraries), but then it can't find the libraries itself (at the "linking" stage). This is a bit weird, and I thought I had fixed it with the `-framework OpenCL` thing in PR #515...

Just so you know what's going on :-D

**Comment by MichaelClerx** [comment]
Seeing this now:
```
/usr/lib64/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'extra_linker_args'
  warnings.warn(msg)
```
Think it should be `extra_link_args` :facepalm:

**Comment by MichaelClerx** [comment]
Weird: https://github.com/enthought/enable/pull/335

**Comment by MichaelClerx** [comment]
Might have fixed this: https://travis-ci.com/github/MichaelClerx/myokit/builds/214258775

**Comment by DavAug** [comment]
> Apparently not working on all OS/X systems.
> 
> @DavAug OpenCL is a framework for GPU/CPU code, that's supported (or definitely used to be) natively by Apple, but also works with nvidia, amd, intel, etc. Myokit uses it for GPU simulations.
> 
> Usually it's a hassle to install, so the unit tests detect that there's no OpenCL and skip the OpenCL tests.
> In your case, it seems that it _can_ find the header files (C/C++ `.h` files, which tell you about compiled libraries), but then it can't find the libraries itself (at the "linking" stage). This is a bit weird, and I thought I had fixed it with the `-framework OpenCL` thing in PR #515...
> 
> Just so you know what's going on :-D

Ok cool thanks! So OpenCL may just have been installed by default then? (I definitely didn't knowingly use OpenCL before). Let me know if I can help debugging this.

**Comment by MichaelClerx** [comment]
Ooh yes please!
Can you download the OpenCL example  from http://myokit.org/examples/#stewart-2009 (3d example, with the rainbow plot)

That shouldn't run on your system, if I understand things correctly

So then find `myokit/_sim/opencl.py` and `myokit/_sim/openclsim.py`.
Inside each there should be a line

  flags.append('-framework OpenCL')

which should be replaced by

  flags.append('-framework')
  flags.append('OpenCL')

Can you try that and see if the example runs?

**Comment by DavAug** [comment]
Just in the mean time while I make the changes, this is the error I get from running the script  atm.

```
WARNING:myokit:Using development version of Myokit (1.32.1.dev).
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/unixccompiler.py", line 204, in link
    self.spawn(linker + ld_args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/unixccompiler.py", line 206, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 198, in _compile
    str('--inplace'),
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    s = myokit.SimulationOpenCL(m, p, ncells=n)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/openclsim.py", line 321, in __init__
    mname, fname, args, libs, libd, incd, larg=flags)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 209, in _compile
    raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command 'clang' failed with exit status 1
Error traceback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/unixccompiler.py", line 204, in link
    self.spawn(linker + ld_args)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/unixccompiler.py", line 206, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/__init__.py", line 198, in _compile
    str('--inplace'),
  File "/Users/david/Workspace/sabs-r3/myokit/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'clang' failed with exit status 1

Compiler output:
    running build_ext
    building 'myokit_sim_opencl_1_3724335078215135418' extension
    creating build
    creating build/temp.macosx-10.15-x86_64-3.7
    creating build/temp.macosx-10.15-x86_64-3.7/var
    creating build/temp.macosx-10.15-x86_64-3.7/var/folders
    creating build/temp.macosx-10.15-x86_64-3.7/var/folders/8w
    creating build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp
    creating build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T
    creating build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp50kp84fcmyokit
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/include/CL -I/usr/local/cuda/include -I/System/Library/Frameworks -I/Users/david/Workspace/sabs-r3/myokit/myokit/_sim -I/Users/david/Workspace/sabs-r3/myokit/myokit/_sim -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/david/Workspace/sabs-r3/myokit/venv/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp50kp84fcmyokit/source.c -o build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp50kp84fcmyokit/source.o
    creating build/lib.macosx-10.15-x86_64-3.7
    clang -bundle -undefined dynamic_lookup build/temp.macosx-10.15-x86_64-3.7/var/folders/8w/b9lb3wb92c1fscyr5tc8nswh0000gp/T/tmp50kp84fcmyokit/source.o -L/usr/lib64 -L/usr/lib64/nvidia -L/usr/local/cuda/lib64 -L/System/Library/Frameworks -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -L/usr/lib64 -L/usr/lib64/nvidia -L/usr/local/cuda/lib64 -L/System/Library/Frameworks -lm -o build/lib.macosx-10.15-x86_64-3.7/myokit_sim_opencl_1_3724335078215135418.cpython-37m-darwin.so -framework OpenCL
    clang: error: unknown argument: '-framework OpenCL'
```

**Comment by DavAug** [comment]
Doesn't crash with the changes! Although the result isn't telling me anything :D .

![Figure_1](https://user-images.githubusercontent.com/20031982/105612581-68008a00-5dbd-11eb-96c7-55f785c73939.png)

**Comment by DavAug** [comment]
> Doesn't crash with the changes! But the result isn't telling me anything :D .
> 
> ![Figure_1](https://user-images.githubusercontent.com/20031982/105612581-68008a00-5dbd-11eb-96c7-55f785c73939.png)

Ahh never mind, it looks pretty similar to the figure here http://myokit.org/examples/#stewart-2009
