### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#671]
```
======================================================================
ERROR: test_convert_unit (test_variable.VariableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/michael/dev/myokit/myokit/tests/test_variable.py", line 88, in test_convert_unit
    m.check_units(myokit.UNIT_STRICT)
  File "/home/michael/dev/myokit/myokit/_model_api.py", line 1018, in check_units
    e = e.eval_unit(mode)
  File "/home/michael/dev/myokit/myokit/_expressions.py", line 316, in eval_unit
    raise result
myokit._err.IncompatibleUnitError: Incompatible units: Addition requires equal units, got [A/F] (or [g*m^2/s^4/A (1000)]) and [uA/cm^2] (or [A/m^2 (0.01)]).
Encountered when evaluating
  -(ikr.i + ina.i / 1 [cm^2/uF] / 1 [cm^2/uF] * 1 [cm^2/uF]) * 0.001 [1 (1000)]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

======================================================================
FAIL: test_unit_conversion (test_formats_easyml.EasyMLExporterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/michael/dev/myokit/myokit/tests/test_formats_easyml.py", line 195, in test_unit_conversion
    self.assertEqual(ob, ex)
AssertionError: 'I1 =[16 chars]V / 1000.0 / 1000.0 / 1000.0 / 1000.0 / 1000.0 - 0.05) * 0.05;' != 'I1 =[16 chars]V / 1000.0 - 0.05) * 0.05;'
- I1 = 3.0 * x * y * (V / 1000.0 / 1000.0 / 1000.0 / 1000.0 / 1000.0 - 0.05) * 0.05;
+ I1 = 3.0 * x * y * (V / 1000.0 - 0.05) * 0.05;


======================================================================
FAIL: test_simulation_error_2 (test_simulation_cvode.SimulationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/michael/dev/myokit/myokit/tests/test_simulation_cvode.py", line 367, in test_simulation_error_2
    self.assertIn('CV_ERR_FAILURE', str(e.exception))
AssertionError: 'CV_ERR_FAILURE' not found in 'A numerical error occurred during simulation at t = 2001.5.\nLast reached state: \n  membrane.V =  2.42224679881812436e-03\n  ina.m      =  9.97719529479536016e-01\n  ina.h      =  6.81502551179032252e-03\n  ina.j      =  8.11611333911107402e-01\n  ica.d      =  2.75946061249164008e-02\n  ica.f      =  9.99354839674998607e-01\n  ik.x       =  9.23130110037218121e-01\n  ica.Ca_i   =  1.80449282051329483e-04\nInputs for binding: \n  time        =  2.00166273998800193e+03\n  pace        = 0.0\n  realtime    =  1.77984270003435086e-02\n  evaluations = 9532.0'

----------------------------------------------------------------------
Ran 987 tests in 76.068s

FAILED (failures=2, errors=1)
```

Third one might actually be a CVODE 5 thing #587

**Comment by MichaelClerx** [comment]
Fixed in #672
