### ISSUE TITLE
Error with msvc compiler after installing opencl

### ISSUE THREAD

**Issue by mbonico** [MichaelClerx/myokit#688]
Hi Michael!

I tried to install opencl but I keep getting the following error when running an example requiring openCL. It does work with the examples that does not require openCL though. It seems like it's related to the msvc compiler so I tried to uninstall and install visual studio 2019 but it keeps giving me the same error. Do you know what might be the problem?

Thanks a lot!

Nicolas

```
[22:01:12] Loading Myokit IDE
[22:01:14] Opened E:\Etudes\Stage ICM\Projet Myokit\examples\decker-2009.mmt
[22:01:28] Running embedded script.
[22:01:34] Done.
[22:01:50] Opened E:\Etudes\Stage ICM\Projet Myokit\OpenCL\stewart-2009-cable-opencl.mmt
[22:01:53] Running embedded script.
[22:01:56] An error has occurred
[22:01:56] Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\distutils\_msvccompiler.py", line 508, in link
    self.spawn([self.linker] + ld_args)
  File "c:\users\mbola\miniconda3\lib\distutils\_msvccompiler.py", line 518, in spawn
    return super().spawn(cmd)
  File "c:\users\mbola\miniconda3\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "c:\users\mbola\miniconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "c:\users\mbola\miniconda3\lib\distutils\spawn.py", line 80, in _spawn_nt
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\users\mbola\miniconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "c:\users\mbola\miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\users\mbola\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "c:\users\mbola\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 550, in build_extension
    self.compiler.link_shared_object(
  File "c:\users\mbola\miniconda3\lib\distutils\ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "c:\users\mbola\miniconda3\lib\distutils\_msvccompiler.py", line 510, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 192, in _compile
    setup(
  File "c:\users\mbola\miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "c:\users\mbola\miniconda3\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\gui\ide.py", line 938, in action_run
    myokit.run(
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_aux.py", line 1134, in run
    r.run()
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_aux.py", line 1125, in run
    myokit._exec(self.script, environment)
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_exec_new.py", line 15, in _exec
    exec(script, globals, locals)
  File "<string>", line 14, in <module>
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\openclsim.py", line 320, in __init__
    self._sim = self._compile(
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 209, in _compile
    raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146
Error traceback
Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\distutils\_msvccompiler.py", line 508, in link
    self.spawn([self.linker] + ld_args)
  File "c:\users\mbola\miniconda3\lib\distutils\_msvccompiler.py", line 518, in spawn
    return super().spawn(cmd)
  File "c:\users\mbola\miniconda3\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "c:\users\mbola\miniconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "c:\users\mbola\miniconda3\lib\distutils\spawn.py", line 80, in _spawn_nt
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\users\mbola\miniconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "c:\users\mbola\miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "c:\users\mbola\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "c:\users\mbola\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "c:\users\mbola\miniconda3\lib\distutils\command\build_ext.py", line 550, in build_extension
    self.compiler.link_shared_object(
  File "c:\users\mbola\miniconda3\lib\distutils\ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "c:\users\mbola\miniconda3\lib\distutils\_msvccompiler.py", line 510, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\__init__.py", line 192, in _compile
    setup(
  File "c:\users\mbola\miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "c:\users\mbola\miniconda3\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe' failed with exit status 1146

Compiler output:
    running build_ext
    building 'myokit_sim_opencl_1_2870234442241405037' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\Users
    creating build\temp.win-amd64-3.8\Release\Users\mbola
    creating build\temp.win-amd64-3.8\Release\Users\mbola\AppData
    creating build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local
    creating build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp
    creating build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Intel\OpenCL SDK\6.3\include" "-IC:\Program Files\AMD APP SDK\2.9\include" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" "-IC:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\include" -I -Ic:\users\mbola\miniconda3\lib\site-packages\myokit\_sim -Ic:\users\mbola\miniconda3\lib\site-packages\myokit\_sim -Ic:\users\mbola\miniconda3\include -Ic:\users\mbola\miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /TcC:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c /Fobuild\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.obj
    source.c
    cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
    c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\mcl.h(683): warning C4244: 'fonction'ÿ: conversion de 'cl_ulong' en 'long', perte possible de donn‚es
    c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\mcl.h(690): warning C4244: 'fonction'ÿ: conversion de 'cl_ulong' en 'long', perte possible de donn‚es
    c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\mcl.h(697): warning C4244: 'fonction'ÿ: conversion de 'cl_ulong' en 'long', perte possible de donn‚es
    c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\mcl.h(711): warning C4267: 'fonction'ÿ: conversion de 'size_t' en 'long', perte possible de donn‚es
    c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\mcl.h(727): warning C4267: 'fonction'ÿ: conversion de 'size_t' en 'long', perte possible de donn‚es
    c:\users\mbola\miniconda3\lib\site-packages\myokit\_sim\mcl.h(736): warning C4267: 'fonction'ÿ: conversion de 'size_t' en 'long', perte possible de donn‚es
    C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c(397): warning C4244: '='ÿ: conversion de 'Py_ssize_t' en 'int', perte possible de donn‚es
    C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c(406): warning C4244: '='ÿ: conversion de 'Py_ssize_t' en 'int', perte possible de donn‚es
    C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c(494): warning C4244: '='ÿ: conversion de 'Py_ssize_t' en 'int', perte possible de donn‚es
    C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c(751): warning C4244: '='ÿ: conversion de 'Py_ssize_t' en 'int', perte possible de donn‚es
    C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c(590): warning C4996: 'clCreateCommandQueue': a ‚t‚ d‚clar‚ d‚conseill‚
    C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.c(1124): warning C4113: 'PyObject *(__cdecl *)()' est diff‚rent de 'PyCFunction' dans les listes de paramŠtres
    creating C:\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\build\build\lib.win-amd64-3.8
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Intel\OpenCL SDK\6.3\lib\x64" "/LIBPATH:C:\Program Files\AMD APP SDK\2.9\bin\x64" "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64" "/LIBPATH:C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\lib\x64" /LIBPATH: /LIBPATH:c:\users\mbola\miniconda3\libs /LIBPATH:c:\users\mbola\miniconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" OpenCL.lib /EXPORT:PyInit_myokit_sim_opencl_1_2870234442241405037 build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.obj /OUT:build\lib.win-amd64-3.8\myokit_sim_opencl_1_2870234442241405037.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\myokit_sim_opencl_1_2870234442241405037.cp38-win_amd64.lib
    Microsoft (R) Incremental Linker Version 14.28.29336.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    LINK : fatal error LNK1146: aucun argument sp‚cifi‚ avec l'option '/LIBPATH:'
```

**Comment by MichaelClerx** [comment]
Hi Nicolas, thanks for reporting.
It looks like the error happens at the "linking" stage, which usually means that myokit can't find the compiled OpenCL libraries (i.e. the DLL files). There should be a file `.config/myokit/myokit.ini` in your user directory, that has a section where you can specify the correct paths

**Comment by MichaelClerx** [comment]
The last line of the error message is the most important one here:

```LINK : fatal error LNK1146: aucun argument sp‚cifi‚ avec l'option '/LIBPATH:'```

It means that something is going wrong at the "linking" stage. So visual studio has compiled the simulation code, and now wants to link it to the shared libraries from OpenCL. But, it seems to complain that "no argument" was specified with LIBPATH.

A few lines above that I can see
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Intel\OpenCL SDK\6.3\lib\x64" "/LIBPATH:C:\Program Files\AMD APP SDK\2.9\bin\x64" "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64" "/LIBPATH:C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\lib\x64" /LIBPATH: /LIBPATH:c:\users\mbola\miniconda3\libs /LIBPATH:c:\users\mbola\miniconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" OpenCL.lib /EXPORT:PyInit_myokit_sim_opencl_1_2870234442241405037 build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\source.obj /OUT:build\lib.win-amd64-3.8\myokit_sim_opencl_1_2870234442241405037.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\Users\mbola\AppData\Local\Temp\tmpdu5doah8myokit\myokit_sim_opencl_1_2870234442241405037.cp38-win_amd64.lib
```

which does include this bit:
```
"/LIBPATH:C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\lib\x64" 
/LIBPATH: 
/LIBPATH:c:\users\mbola\miniconda3\libs
```

I'm guessing that might be due to the empty spaces in your ini file argument, or perhaps it's because the line ends with `;` ?

If you can remove the trailing `;`s in your `myokit.ini` file and let me know if that fixes it, I can write some code to do this automatically from now on!

**Comment by MichaelClerx** [comment]
So update the `ini` file to just this:

```
[opencl]
# Location of opencl shared libary files (.so or .dll).
# Multiple paths can be set using ; as separator.
lib = C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\lib\x64
# Location of opencl header files (.h).
inc = C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\include
```

(You don't need the other paths, they are just provided as likely paths that might exist on users system)

**Comment by mbonico** [comment]
So I tried to update my ini file as you advised but I am still getting the same error message. Here's my file :

[opencl]
# Location of opencl shared libary files (.so or .dll).
# Multiple paths can be set using ; as separator.
lib = C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\lib\x64 
# Location of opencl header files (.h).
inc = C:\Program Files (x86)\IntelSWTools\system_studio_2020\OpenCL\sdk\include

**Comment by MichaelClerx** [comment]
Can you show me the error message again?

**Comment by mbonico** [comment]
Hey actually I just needed to restart my computer after updating my ini file as you advised, and now it's working! So the problem was the semicolon and the space in my lib path.

Thanks a lot and have a good day!

Nicolas
