### ISSUE TITLE
Automatic tests from myokit/test fail

### ISSUE THREAD

**Issue by teosbpl** [MichaelClerx/myokit#74]
Tests from myokit/test dir fail.

teos@kostek:/data/projects/elfizjo_lab/HH/myokit/test$ python all
 Running run 
Scanning for tests
Adding expressions
Adding importers
Adding meta
Adding pacing
Adding exporters
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/run", line 12, in <module>
    result = myotest.cmd()
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/myotest/__init__.py", line 63, in cmd
    return run_all()
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/myotest/__init__.py", line 101, in run_all
    suite.addTests(mod.suite())
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/myotest/exporters.py", line 24, in suite
    for name in myokit.formats.exporters():
  File "build/bdist.linux-x86_64/egg/myokit/formats/__init__.py", line 111, in exporters
  File "build/bdist.linux-x86_64/egg/myokit/formats/__init__.py", line 574, in _update
OSError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/formats'
Errors found in "run"
Halting
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
teos@kostek:/data/projects/elfizjo_lab/HH/myokit/test$ python pub
Loading test-example-ttp-7-transmural-plane.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 37, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/openclsim.py", line 242, in __init__
    self._sim = self._compile(mname, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/openclsim.c'

----------------------------------------------------------------------
Loading test-example-ttp-5-transmural-baseline.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 33, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/openclsim.py", line 242, in __init__
    self._sim = self._compile(mname, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/openclsim.c'

----------------------------------------------------------------------
Loading test-example-parameter-estimation-2.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 102, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Loading test-example-ttp-4-sensitivity.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 25, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/psim.py", line 180, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/psim.cpp'

----------------------------------------------------------------------
Loading test-example-multi-model-testing.mmt
Running...
Loaded benson-2008-endo
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 42, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Loading test-example-ttp-6-transmural-modified.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 35, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/openclsim.py", line 242, in __init__
    self._sim = self._compile(mname, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/openclsim.c'

----------------------------------------------------------------------
Loading test-tran-2009-compact.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Loading test-example-ttp-2-transmural-differences.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 26, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Loading test-example-ttp-1-model.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 32, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Loading test-example-parameter-estimation.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 36, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Loading test-example-ttp-3-gto.mmt
Running...
Traceback (most recent call last):
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 47, in run
    myokit.run(m, p, x)
  File "build/bdist.linux-x86_64/egg/myokit/_aux.py", line 977, in run
    exec self.script in environment
  File "<string>", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/myokit/_sim/cvode.py", line 130, in __init__
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 94, in _compile
    self._export(tpl, tpl_vars, src_file)
  File "build/bdist.linux-x86_64/egg/myokit/_sim/__init__.py", line 168, in _export
    result = p.process(source, varmap)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 62, in process
    script = self._convert(filename)
  File "build/bdist.linux-x86_64/egg/myokit/pype.py", line 140, in _convert
    with open(source, 'r') as f:
IOError: [Errno 2] No such file or directory: 'build/bdist.linux-x86_64/egg/myokit/_sim/cvode.c'

----------------------------------------------------------------------
Done!
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq

teos@kostek:data/projects/elfizjo_lab/HH/myokit/test$ python web
Traceback (most recent call last):
  File "web", line 33, in <module>
    run(path_examples)
  File "/home/teos/data/projects/elfizjo_lab/HH/myokit/test/runner.py", line 28, in run
    os.chdir(path)
OSError: [Errno 2] No such file or directory: '/home/teos/data/projects/elfizjo_lab/HH/myokit/web/html/static/download/data/examples'

**Comment by MichaelClerx** [comment]
Thanks! Did you run `python setup.py develop` before running these tests?

**Comment by teosbpl** [comment]
Touche!
After sudo python setup.py develop one test fails anyway:
python pub
Loading test-example-ttp-7-transmural-plane.mmt
Running...
python: /build/beignet-5qGeBM/beignet-1.1.1/src/intel/intel_driver.c:140: intel_driver_context_init: Assertion `driver->ctx' failed.

**Comment by teosbpl** [comment]
The rest goes OK

**Comment by MichaelClerx** [comment]
Thanks! I still need to fix it so that the tests run without the development install (#72). The failing test seems to be an OpenCL one. Did other OpenCL tests (e.g. `$ test/unit-full.py simulation_opencl`) pass ?

**Comment by MichaelClerx** [comment]
These are no longer part of the main test framework now. Unit tests all check for OpenCL support before running (see #89), so closing this issue now!
