### ISSUE TITLE
Various errors and warnings when compiling OpenCL kernels

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#749]
On @DavAug 's machine at least :-D

```
OpenCL Error: Fiber kernel failed to compile.
-------------------------------------------------------------------------------
<program source>:66:6: warning: no previous prototype for function 'calc_membrane'
void calc_membrane(const uint of1, const uint of2, const uint of3, __global Real *state, __global Real *inter_log, const __global Real *field_data, Real V_IK, Real V_IK1, Real V_IKp, Real V_INa, Real V_Ib, Real pace, Real idiff, __private Real *D_V)
     ^
<program source>:76:6: warning: no previous prototype for function 'calc_ina'
void calc_ina(const uint of1, const uint of2, const uint of3, __global Real *state, __global Real *inter_log, const __global Real *field_data, __private Real *V_INa, __private Real *D_h, __private Real *D_j, __private Real *D_m)
     ^
```

**Comment by MichaelClerx** [comment]
```
<program source>:78:35: error: call to '__fast_relax_exp' is ambiguous
    Real V_a = 1.0 - 1.0 / (1.0 + exp((-(V_V + 40.0)) / 0.24));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4544:22: note: expanded from macro 'exp'
    #define exp(__x) __fast_relax_exp(__x)
                     ^~~~~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4542:30: note: candidate function
    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_exp, native_exp, __cl_exp);
                             ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:417:27: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float __OVERLOAD__ _name(float x) { return _default_name(x); } \
                          ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4542:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:418:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float2 __OVERLOAD__ _name(float2 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4542:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:419:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float3 __OVERLOAD__ _name(float3 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4542:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:420:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float4 __OVERLOAD__ _name(float4 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4542:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:421:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float8 __OVERLOAD__ _name(float8 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4542:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:422:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float16 __OVERLOAD__ _name(float16 x){ return _default_name(x); }
                            ^
```

```
<program source>:82:22: error: call to '__cl_pow' is ambiguous
    *V_INa = V_gNa * pow(V_m, 3.0) * V_h * V_j * (V_V - V_ENa);
                     ^~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4709:27: note: expanded from macro 'pow'
    #define pow(__x, __y) __cl_pow(__x, __y)
                          ^~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4706:15: note: candidate function
__CLFN_FD_2FD(__cl_pow);
              ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:1010:48: note: expanded from macro '__CLFN_FD_2FD'
#define __CLFN_FD_2FD(name) float __OVERLOAD__ name(float x, float y); \
                                               ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4706:15: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:1011:21: note: expanded from macro '__CLFN_FD_2FD'
float2 __OVERLOAD__ name(float2 x, float2 y); \
                    ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4706:15: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:1012:21: note: expanded from macro '__CLFN_FD_2FD'
float3 __OVERLOAD__ name(float3 x, float3 y); \
                    ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4706:15: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:1013:21: note: expanded from macro '__CLFN_FD_2FD'
float4 __OVERLOAD__ name(float4 x, float4 y); \
                    ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4706:15: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:1014:21: note: expanded from macro '__CLFN_FD_2FD'
float8 __OVERLOAD__ name(float8 x, float8 y); \
                    ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4706:15: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:1015:22: note: expanded from macro '__CLFN_FD_2FD'
float16 __OVERLOAD__ name(float16 x, float16 y);
                     ^
```

These all look like they could be related to literals, but then there's also:

```
<program source>:100:40: error: call to '__fast_relax_log' is ambiguous
    *V_IK = V_gK * V_xi * V_x * (V_V - V_ik_E);
                                       ^~~~~~
<program source>:40:25: note: expanded from macro 'V_ik_E'
#define V_ik_E (V_RTF * log((V_K_o + V_PNa_K * V_Na_o) / (V_K_i + V_PNa_K * V_Na_i)))
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4655:22: note: expanded from macro 'log'
    #define log(__x) __fast_relax_log(__x)
                     ^~~~~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4653:30: note: candidate function
    __CLFN_FD_1FD_FAST_RELAX(__fast_relax_log, native_log, __cl_log);
                             ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:417:27: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float __OVERLOAD__ _name(float x) { return _default_name(x); } \
                          ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4653:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:418:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float2 __OVERLOAD__ _name(float2 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4653:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:419:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float3 __OVERLOAD__ _name(float3 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4653:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:420:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float4 __OVERLOAD__ _name(float4 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4653:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:421:28: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float8 __OVERLOAD__ _name(float8 x) { return _default_name(x); } \
                           ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:4653:30: note: candidate function
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/lib/clang/3.5/include/cl_kernel.h:422:29: note: expanded from macro '__CLFN_FD_1FD_FAST_RELAX'
inline float16 __OVERLOAD__ _name(float16 x){ return _default_name(x); }
                            ^
<program source>:106:6: warning: no previous prototype for function 'calc_ikp'
void calc_ikp(const uint of1, const uint of2, const uint of3, __global Real *state, __global Real *inter_log, const __global Real *field_data, __private Real *V_IKp)
     ^
```

**Comment by MichaelClerx** [comment]
Only three tests fail:

```
======================================================================
ERROR: test_against_cvode (__main__.FiberTissueSimulationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "myokit/tests/test_simulation_opencl.py", line 984, in test_against_cvode
    d1, logt = s1.run(tmax, logf=logvars, logt=logt, log_interval=dlog)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/fiber_tissue.py", line 710, in run
    duration, logf, logt, log_interval, report_nan, progress, msg)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/fiber_tissue.py", line 874, in _run
    [x.qname().encode('ascii') for x in inter_logt],
Exception: OpenCL error: CL_BUILD_PROGRAM_FAILURE

======================================================================
ERROR: test_against_cvode (__main__.SimulationOpenCL0dTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "myokit/tests/test_simulation_opencl.py", line 56, in test_against_cvode
    d1 = s1.run(tmax, logvars, log_interval=dt).npview()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/openclsim.py", line 906, in run
    r = self._run(duration, log, log_interval, report_nan, progress, msg)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/openclsim.py", line 1022, in _run
    field_data,
Exception: OpenCL error: CL_BUILD_PROGRAM_FAILURE

======================================================================
ERROR: test_connections_simple_double_precision (__main__.SimulationOpenCLTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "myokit/tests/test_simulation_opencl.py", line 564, in test_connections_simple_double_precision
    d1a = s1.run(t, log=log, log_interval=0.1).npview()
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/openclsim.py", line 906, in run
    r = self._run(duration, log, log_interval, report_nan, progress, msg)
  File "/Users/david/Workspace/sabs-r3/myokit/myokit/_sim/openclsim.py", line 1022, in _run
    field_data,
Exception: OpenCL error: CL_BUILD_PROGRAM_FAILURE
```

**Comment by MichaelClerx** [comment]
All three failing tests use double precision, so literals are correct

**Comment by MichaelClerx** [comment]
Can't find much on why this would happen. Except that the device maybe doesn't support doubles (but fails to raise an error when the extension is enabled)

https://www.ghcc.net/node/1012883

**Comment by MichaelClerx** [comment]
None of the "ambiguous overloads" are actually appropriate, since the operations are with doubles, not floats. The ambiguity comes from trying to cast to float

**Comment by MichaelClerx** [comment]
From @DavAug 👍🏻 

```
Platform 0
 Name       : Apple
 Vendor     : Apple
 Version    : OpenCL 1.2 (Jun  8 2020 17:36:15)
 Profile    : FULL_PROFILE
 Extensions : cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
```

So extension is not present! Will try to add a check before running then...
