### ISSUE TITLE
Add sundials 6.0.0 support

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#819]
https://computing.llnl.gov/projects/sundials/release-history

**Comment by MichaelClerx** [comment]
```
======================================================================
ERROR: test_run (test_aux.AuxTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/myokit/myokit/myokit/tests/test_aux.py", line 283, in test_run
    myokit.run(m, p, x)
  File "/home/runner/work/myokit/myokit/myokit/_aux.py", line 523, in run
    r.run()
  File "/home/runner/work/myokit/myokit/myokit/_aux.py", line 514, in run
    myokit._exec(self.script, environment)
  File "/home/runner/work/myokit/myokit/myokit/_exec_new.py", line 15, in _exec
    exec(script, globals, locals)
  File "<string>", line 5, in <module>
  File "/home/runner/work/myokit/myokit/myokit/_sim/cvodessim.py", line 152, in __init__
    self._create_simulation(cmodel.code)
  File "/home/runner/work/myokit/myokit/myokit/_sim/cvodessim.py", line 221, in _create_simulation
    self._sim = self._compile(module_name, fname, args, libs, libd, incd)
  File "/home/runner/work/myokit/myokit/myokit/_sim/__init__.py", line 213, in _compile
    raise myokit.CompilationError('\n'.join(t))
myokit._err.CompilationError: Unable to compile.
Error message:
error: command '/usr/bin/gcc' failed with exit code 1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/distutils/spawn.py", line 91, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
          |               ^~~
    /tmp/tmpbc0pzke8myokit/source.c:1141:20: warning: unused variable ‘l2’ [-Wunused-variable]
     1141 |     PyObject *l1, *l2;
          |                    ^~
    /tmp/tmpbc0pzke8myokit/source.c: In function ‘sim_init’:
    /tmp/tmpbc0pzke8myokit/source.c:1941:9: error: too few arguments to function ‘N_VNew_Serial’
     1941 |     y = N_VNew_Serial(model->n_states);
          |         ^~~~~~~~~~~~~
    In file included from /tmp/tmpbc0pzke8myokit/source.c:7:
    /usr/local/include/nvector/nvector_serial.h:85:26: note: declared here
       85 | SUNDIALS_EXPORT N_Vector N_VNew_Serial(sunindextype vec_length, SUNContext sunctx);
          |                          ^~~~~~~~~~~~~
    /tmp/tmpbc0pzke8myokit/source.c:1947:13: error: too few arguments to function ‘N_VNew_Serial’
     1947 |     ylast = N_VNew_Serial(model->n_states);
          |             ^~~~~~~~~~~~~
    In file included from /tmp/tmpbc0pzke8myokit/source.c:7:
    /usr/local/include/nvector/nvector_serial.h:85:26: note: declared here
       85 | SUNDIALS_EXPORT N_Vector N_VNew_Serial(sunindextype vec_length, SUNContext sunctx);
          |                          ^~~~~~~~~~~~~
    /tmp/tmpbc0pzke8myokit/source.c:1975:13: error: too few arguments to function ‘N_VNew_Serial’
     1975 |         z = N_VNew_Serial(model->n_states);
          |             ^~~~~~~~~~~~~
    In file included from /tmp/tmpbc0pzke8myokit/source.c:7:
    /usr/local/include/nvector/nvector_serial.h:85:26: note: declared here
       85 | SUNDIALS_EXPORT N_Vector N_VNew_Serial(sunindextype vec_length, SUNContext sunctx);
          |                          ^~~~~~~~~~~~~
    /tmp/tmpbc0pzke8myokit/source.c:2134:21: error: too few arguments to function ‘CVodeCreate’
     2134 |         cvode_mem = CVodeCreate(CV_BDF); /* Newton is still default */
          |                     ^~~~~~~~~~~
    In file included from /tmp/tmpbc0pzke8myokit/source.c:6:
    /usr/local/include/cvodes/cvodes.h:183:23: note: declared here
      183 | SUNDIALS_EXPORT void *CVodeCreate(int lmm, SUNContext sunctx);
          |                       ^~~~~~~~~~~
    /tmp/tmpbc0pzke8myokit/source.c:2162:31: error: too few arguments to function ‘SUNDenseMatrix’
     2162 |             sundense_matrix = SUNDenseMatrix(model->n_states, model->n_states);
          |                               ^~~~~~~~~~~~~~
    In file included from /tmp/tmpbc0pzke8myokit/source.c:14:
    /usr/local/include/sunmatrix/sunmatrix_dense.h:79:27: note: declared here
       79 | SUNDIALS_EXPORT SUNMatrix SUNDenseMatrix(sunindextype M, sunindextype N, SUNContext sunctx);
          |                           ^~~~~~~~~~~~~~
    /tmp/tmpbc0pzke8myokit/source.c:2166:31: error: too few arguments to function ‘SUNLinSol_Dense’
     2166 |             sundense_solver = SUNLinSol_Dense(y, sundense_matrix);
          |                               ^~~~~~~~~~~~~~~
    In file included from /tmp/tmpbc0pzke8myokit/source.c:15:
    /usr/local/include/sunlinsol/sunlinsol_dense.h:58:33: note: declared here
       58 | SUNDIALS_EXPORT SUNLinearSolver SUNLinSol_Dense(N_Vector y, SUNMatrix A, SUNContext sunctx);
          |                                 ^~~~~~~~~~~~~~~

```
