### ISSUE TITLE
CL_PLATFORM_NOT_FOUND_KHR (re)occuring

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#856]
Thought this was fixed, but getting a report with this myokit system output:

```
== System information == 
Myokit: 1.33.1 
Python: 3.7.12 (default, Jan 15 2022, 18:48:18) [GCC 7.5.0]
OS: Linux (linux, posix) 

== Python requirements ==
NumPy: 1.21.5
SciPy: 1.4.1
Matplotlib: 3.2.2
ConfigParser: OK
Setuptools: 57.4.0

== Python extras ==
SymPy: 1.7.1
MoviePy: 0.2.3.5 

== GUI == 
PyQt5: Not found 
PyQt4: Not found 
PySide: Not found
PySide2: Not found

== Development tools ==
Sphinx: 1.8.6 
Flake8: Not found 

== Simulation tools ==
Compiler: GCC 7.5.0
Sundials: 2.7.0
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)   
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals)   
  File "/usr/local/lib/python3.7/dist-packages/myokit/__main__.py", line 2203, in <module> main()   
  File "/usr/local/lib/python3.7/dist-packages/myokit/__main__.py", line 85, in main func(**args)   
  File "/usr/local/lib/python3.7/dist-packages/myokit/__main__.py", line 1222, in system
    myokit.system(live_printing=True)   
  File "/usr/local/lib/python3.7/dist-packages/myokit/_system.py", line 114, in system
    for p in opencl.info().platforms:   
  File "/usr/local/lib/python3.7/dist-packages/myokit/_sim/opencl.py", line 126, in info
    info = OpenCLInfo(OpenCL._get_instance().info())
Exception: OpenCL error: CL_PLATFORM_NOT_FOUND_KHR
```

**Comment by MichaelClerx** [comment]
Can reproduce this with
- A VM running Ubuntu 18.04.6 LTS
- Myokit 1.33.1
- `apt-get install ocl-icd-opencl-dev`

**Comment by MichaelClerx** [comment]
```
#!/usr/bin/env python3
import myokit
opencl = myokit.OpenCL()

if not opencl.supported():  # pragma: no cover
    print('OpenCL: No OpenCL support detected.')
else:   # pragma: no cover
    devices = []
    for p in opencl.info().platforms:
        for d in p.devices:
            devices.append(d.name + ' on ' + p.name)
    print('OpenCL: ' + str(len(devices)) + ' device(s) found')
    for d in devices:
        print('  ' + d)
    print('  Use `python -m myokit opencl` for more information.')
```
